services:
  server:
    build: .
    ports:
      - "8000:${SERVER_PORT}"
    environment:
      JWT_SECRET: ${JWT_SECRET}
      SERVER_PORT: ${SERVER_PORT}
      MONGODB_URI: ${MONGODB_URI}
      REDIS_URI: ${REDIS_URI}
    develop:
      watch:
        - path: ./
          target: /app/
          action: rebuild
          ignore:
            - .git/
              tmp/
              tags
  redis:
    image: redis
    command: bash -c "echo 'aclfile /run/secrets/acl' | redis-server -"
    ports:
      - 8001:${REDIS_PORT}
    secrets:
      - acl

secrets:
  acl:
    file: ./users.acl
